
      function Tagline() {
         var tagline = new Array(
			"We connect <span id='groupOfPeople'></span> with <span id='groupOfPeople2'></span>.",
			"We help <span id='groupOfPeople'></span> find <span id='pluralNoun'></span>.",
			"<span id='verb'></span> <span id='pluralNoun'></span> directly from <span id='groupOfPeople'></span>.",
			"<span id='servicefor'></span> for <span id='groupOfPeople'></span>.",
			"<span id='servicefor'></span> for <span id='groupOfPeople'></span>.",
			"<span id='badProblem'></span> with help from <span id='groupOfPeople'></span>.",
			"Receive a personalized box of <span id='box'></span> each month, hand-picked by <span id='groupOfPeople'></span>."
			);
         var pluralNoun = [ //Buy or rent X from a group of people
			"to-do lists",
			"passwords",
			"storage units",
			"furniture",
			"data models",
			"iPhones",
			"Bitcoins",
			"advertising",
			"handcrafted goods",
			"traditional IRAs",
			"Roth IRAs",
			"extra cloud storage space",
			"hashtags",
			"yachts",
			"real estate",
			"used cars",
			"luxury goods",
			"apartments",
			"firearms",
			"video games",
			"comic books",
			"JavaScript libraries",
			"designer fashions",
			"parking spaces",
			"streaming music, but only jazz",
			"PDF files",
		];
		var buzzyAdj = [
			"vertically integrated",
			"next generation",
			"the world's first",
			"ethically sourced",
			"independent",
			"minimalist",
			"trusted",
			"cutting edge",
			"the largest online",
			"innovative",
		]
		var serviceFor = [ //for a group of people
			"Big data",
			"Data analytics",
			"Video conferencing",
			"A new form of email marketing",
			"The largest online marketplace",
			"Content discovery",
			"Sleek, minimalist app design",
			"A crowdsourced Q&A platform",
			"Fault-tolerant, distributed databases",
			"Ride sharing",
			"Social shopping",
			"A social network",
			"Smart online dating",
			"Coupons exclusively",
			"Parenting tips",
			"Car insurance",
			"Event tickets",
			"DIY tutorials",
			"Integrated bug tracking",
			"A lightweight BitTorrent client",
			"Delicious Asian-Swedish fusion cuisine",
			"Ethically sourced gourmet meals",
			"Customer relationship management",
			"Cloud storage",
			"Vertically integrated cloud storage",
			"Groupon",
			"Twitter",
			"Craigslist",
			"Uber",
			"Tinder",
			"Airbnb",
			"Etsy",
			"Amazon",
			"Zappos",
			"Microloans",
			"Next generation payments",
			"Automatic scheduling",
			"Making the world a better place",
			"Virtual reality",
			"Scalable app development",
			"Streaming radio",
			"Credit card processing",
			"A wearable fitness tracker",
			"A team communication platform",
			"Local event discovery",
			"Gamified learning",
			"Trusted local reviews by and ",
			"Ancestry and lineage discovery",
			"A health insurance marketplace",
		];
		var badProblem = [ //with help from a group of people
			"Remodel your garage",
			"Find your perfect apartment",
			"Find a blind date",
			"Find your perfect match",
			"Find a roommate",
			"Address your janitorial needs",
			"See the history of your used car",
			"Figure out how much to tip",
			"Reach inbox 0",
			"Remember to drink more water",
			"Take care of your grandparents",
			"Discover new things",
			"Find the perfect PhD program",
			"Diversify your portfolio",
			"Scale your app",
			"Grow your business",
			"Never miss a home delivery again",
			"Translate any document",
			"Book flights",
			"Real-time navigation",
			"Mobile news aggregation",
			"Fundraise medical bills",
			"Improve bad posture",
			"Improve work-life balance",
			"Manage your social media presence",
			"Fund your creative project",
			"Plan your next vacation",
			"Pack the best lunches",
			"Build a website",
			"Divide your restaurant check",
			"Find available shelter pets",
			"Find the best hostels in Europe",
			"Get groceries delivered",
			"Address your database management needs",
			"Feed your interns",
			"Replace your uncomfortable furniture"
		];
		var boxContents = [ //personalized box of [things] hand-picked by our staff of X
			"neckties",
			"orchard-grown fruit",
			"toiletries",
			"sushi",
			"craft beer",
			"handmade soaps",
			"nail polish",
			"stylish accessories",
			"bamboo utensils",
			"feminine hygeine products",
			"stationary",
			"wines",
			"crafting supplies",
			"the latest tech",
			"GRE study materials",
			"baby products",
			"dog fashions",
			"fire safety equipment",
			"indie comics",
			"Japanese films",
			"pet medications",
			"t-shirts",
			"literary classics",
			"<em>New York Times</em> best sellers",
		];
		var verbs = [
			"Rent",
			"Buy"
		];
		var groupOfPeople = [
			"cats",
			"dogs",
			"caterers",
			"milennials",
			"scientists",
			"researchers",
			"local families",
			"civil engineers",
			"retail employees",
			"recently fired employees",
			"social media influencers",
			"angel investors",
			"personal style consultants",
			"new parents",
			"happy couples",
			"retailers",
			"top executives",
			"teens",
			"educators",
			"your friends",
			"your parents' friends",
			"your siblings",
			"entrepreneurs",
			"stay-at-home parents",
			"wedding planners",
			"graduate students",
			"undergraduate students",
			"foreign exchange students",
			"unpaid interns",
			"creatives",
			"politicians",
			"LGBT youth",
			"cab drivers",
			"bus drivers",
			"Mormons",
			"litigators",
			"programmers",
			"off-duty police officers",
			"quality assurance associates",
			"front-end developers",
			"back-end developers",
			"web designers",
			"dev ops engineers",
			"MBAs",
			"expats",
			"the Amish",
			"drug dealers",
			"ex-convicts",
			"social justice advocates",
			"feminists",
			"gun owners",
			"small business owners",
			"Swedish people",
			"tech support workers",
			"immigrants",
			"identical twins",
			"fraternal twins",
			"film producers",
			"film critics",
			"journalists",
			"line cooks",
			"recording artists",
			"tax professionals",
			"veterans",
			"clergy members",
			"underemployed people",
			"baby boomers",
			"authors",
			"adjunct professors",
			"academics",
			"content creators",
			"comic artists",
			"postal workers",
			"retirees",
			];
			
         var randomTagline = Math.floor(Math.random()* tagline.length);
         $("#tagline").html(tagline[randomTagline]);
		 
         var randomProblem = Math.floor(Math.random()* badProblem.length);
         $("#badProblem").html(badProblem[randomProblem]);
		 
         var randomVerb = Math.floor(Math.random()* verbs.length);
         $("#verb").html(verbs[randomVerb]);
		 
		  var randomPluralNoun = Math.floor(Math.random()* pluralNoun.length);
         $("#pluralNoun").html(pluralNoun[randomPluralNoun]);
		 
         var randomBox = Math.floor(Math.random()* boxContents.length);
         $("#box").html(boxContents[randomBox]);
		 
		  var randomgroupOfPeople = Math.floor(Math.random()* groupOfPeople.length);
		  var randomgroupOfPeople2 = Math.floor(Math.random()* groupOfPeople.length);
         $("#groupOfPeople").html(groupOfPeople[randomgroupOfPeople]);
         $("#groupOfPeople2").html(groupOfPeople[randomgroupOfPeople2]);
		 
		 var randomService = Math.floor(Math.random()* serviceFor.length);
         $("#servicefor").html(serviceFor[randomService]);

      }